Update generage_pack.yml

diff --git a/.github/workflows/generage_pack.yml b/.github/workflows/generage_pack.yml
--- a/.github/workflows/generage_pack.yml
+++ b/.github/workflows/generage_pack.yml
@@ -25,7 +25,21 @@ jobs:
         run: |
           echo '${{ steps.file_changes.outputs.all_changed_files}}'
 
-      - run: git clone ${{ secrets.SOURCE_REPOSITORY }} wb_upper_tool ; if ($?) { echo "Clone successful" } else { echo "Failed to clone repository" }
+      - name: Clone wb_upper_tool with PAT
+        shell: powershell
+        env:
+          ACCESS_TOKEN: ${{secrets.SOURCE_REPOSITORY}}
+        run: |
+          $url = "https://$env:ACCESS_TOKEN@github.com/VertorWang/wb_upper_tool.git"
+          git clone $url wb_upper_tool
+
+           if ($LASTEXITCODE -eq 0) {
+              echo "Clone successful"
+            } else {
+              echo "Failed to clone repository"
+              exit 1
+            }
+  
 
       - name: Set up Python 3.8
         uses: actions/setup-python@v3
